const { spawn } = require('child_process');
const path = require('path');

const env = {
  // Before the spread, so a developer's .env still wins.
  APP_DEFAULT_USER: 'slim@demo.ch',
  APP_DEFAULT_PASSWORD: '1234',
  PORT: process.env.PORT || '3333',
  API_PORT: process.env.API_PORT || process.env.PORT || '3333',
  ...process.env,

  // Forced, after the spread: the test environment must not be inherited.
  APP_ENV: 'development',
  // Every spec opens a fresh browser context that restores the shared session
  // through /api/auth/*. On a fast CI runner that is 20+ calls per minute — the
  // production limit (20/min, app.module.ts) then answers 429, the app drops to
  // the login page and every spec in that minute fails (retries keep the
  // window exhausted). Must sit after the spread: playwright.config.ts loads
  // .env / .env.example (API_RATE_LIMIT_AUTH=20) into process.env before this
  // script runs, so a `||` default never applied. The e2e API is throwaway.
  API_RATE_LIMIT_AUTH: '1000',
  APP_SECRET: 'test',
  API_AUTH_TEMPLATE_USE_EMAIL_TABLE: 'true',
  API_SESSION_APP_ROLE_NAME: '1',
  API_AUTH_PASSWORD_MIN_LENGTH: '4',
  // All specs share one storageState (one refresh token); a lifetime longer
  // than the suite means no rotation and no replay revocation mid-run.
  APP_SECRET_DURATION_EXPIRATION: '12h',
  // The generated client is regenerated by the dev API, not by the e2e API.
  API_SWAGGER_GENERATE_CLIENT: '0',
  API_SECRET: 'test',

  // In-memory schema for every run, so specs start from a clean state.
  DB_SYNC: '1',
  DB_TYPE: 'sqlite',
  DB_DATABASE: ':memory:',

  TZ: 'UTC',
};

const isWindows = process.platform === 'win32';
const cmd = isWindows ? 'npx.cmd' : 'npx';

const child = spawn(cmd, ['nx', 'serve', 'api'], {
  stdio: 'inherit',
  env,
  cwd: path.resolve(__dirname, '..'),
  shell: isWindows,
});

child.on('exit', (code) => process.exit(code));
process.on('SIGTERM', () => child.kill('SIGTERM'));
process.on('SIGINT', () => child.kill('SIGINT'));
